[package]
name = "key-lang"
version = "0.1.6"
edition = "2021"
description = "To be the prettiest and simpliest script"
license = "MPL-2.0"
repository = "https://github.com/bylx666/key-native"
homepage = "https://docs.subkey.top"
documentation = "https://docs.subkey.top/native"
