name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update nightly && rustup default nightly
      - run: cargo build --release --verbose
      - uses: actions/upload-artifact@v4
        with: 
          name: releasing
          path: target/release/*.(exe|dll)
      - uses: actions/download-artifact@v4
        with:
          name: releasing

